=== frunkis/Ccr/Ccr.MaterialDesign/Resources/Schemas/types.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="types"
        targetNamespace="http://ccr.org/types.xsd"
        elementFormDefault="qualified"
        xmlns="http://ccr.org/types.xsd"
        xmlns:cplx="http://www.w3.org/TR/xmlschema-2"
        xmlns:vs="http://schemas.microsoft.com/Visual-Studio-Intellisense"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        vs:friendlyname="Ccr XSD Schema Type Declarations"
        vs:ishtmlschema="false"
        vs:iscasesensitive="false"
        vs:requireattributequotes="true">

  <xs:simpleType name="typedef_HexColorLiteral">
    <xs:restriction base="xs:string">
      <xs:pattern value="#[A-F0-9]{6}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typedef_LuminosityLiteral">
    <xs:restriction base="xs:string">
      <xs:pattern value="[P|A]{1}[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="typedef_Brush">
    <xs:attribute name="Color" 
                  type="typedef_HexColorLiteral"/>
    <xs:attribute name="Luminosity" 
                  type="typedef_LuminosityLiteral"/>
  </xs:complexType>
  
  <xs:simpleType name="typedef_SwatchIdentifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{1}[A-z ]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="typedef_Swatch">
    <xs:sequence>
      <xs:element name="Brush" 
                  type="typedef_Brush"
                  minOccurs="0" 
                  maxOccurs="unbounded">
        <xs:unique name="key_BrushColorIdentifier">
          <xs:selector xpath="*/typedef_Brush"/>
          <xs:field xpath="Color"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="SwatchIdentifier" 
                  type="typedef_SwatchIdentifier"/>
  </xs:complexType>

  <xs:complexType name="typedef_MDH_Classification"
                  abstract="true">
  </xs:complexType>

  <xs:complexType name="typedef_Palette">
    <xs:sequence>
      <xs:element name="Swatch" 
                  type="typedef_Swatch"
                  minOccurs="0" 
                  maxOccurs="unbounded">
        <xs:unique name="key_SwatchIdentifierIdentifier">
          <xs:selector xpath="*/typedef_Swatch"/>
          <xs:field xpath="SwatchIdentifier"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="typedef_MDH">
    <xs:choice>
      <xs:element name="Palette" 
                  type="typedef_Palette"/>
    </xs:choice>
  </xs:complexType>

  <xs:element name="MDH" type="typedef_MDH"/>

</xs:schema>

=== frunkis/Ccr/Ccr.MaterialDesign/Resources/MetaResources/MDH.xml
<?xml version="1.0" encoding="utf-8" ?>
<MDH xmlns="http://ccr.org/types.xsd"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="
     http://ccr.org/types 
     ../Schemas/types.xsd">

  <Palette>
    <Swatch SwatchIdentifier="Cyan">
      <Brush Luminosity="P050" Color="#E0F7FA"/>
      <Brush Luminosity="P100" Color="#B2EBF2"/>
      <Brush Luminosity="P200" Color="#80DEEA"/>
      <Brush Luminosity="P300" Color="#4DD0E1"/>
      <Brush Luminosity="P400" Color="#26C6DA"/>
      <Brush Luminosity="P500" Color="#00BCD4"/>
      <Brush Luminosity="P600" Color="#00ACC1"/>
      <Brush Luminosity="P700" Color="#0097A7"/>
      <Brush Luminosity="P800" Color="#00838F"/>
      <Brush Luminosity="P900" Color="#006064"/>
      <Brush Luminosity="A100" Color="#84FFFF"/>
      <Brush Luminosity="A200" Color="#18FFFF"/>
      <Brush Luminosity="A400" Color="#00E5FF"/>
      <Brush Luminosity="A700" Color="#00B8D4"/>
    </Swatch>
    <Swatch SwatchIdentifier="Blue">
      <Brush Luminosity="P050" Color="#E0F7FA"/>
      <Brush Luminosity="P100" Color="#B2EBF2"/>
      <Brush Luminosity="P200" Color="#80DEEA"/>
      <Brush Luminosity="P300" Color="#4DD0E1"/>
      <Brush Luminosity="P400" Color="#26C6DA"/>
      <Brush Luminosity="P500" Color="#00BCD4"/>
      <Brush Luminosity="P600" Color="#00ACC1"/>
      <Brush Luminosity="P700" Color="#0097A7"/>
      <Brush Luminosity="P800" Color="#00838F"/>
      <Brush Luminosity="P900" Color="#006064"/>
      <Brush Luminosity="A100" Color="#84FFFF"/>
      <Brush Luminosity="A200" Color="#18FFFF"/>
      <Brush Luminosity="A400" Color="#00E5FF"/>
      <Brush Luminosity="A700" Color="#00B8D4"/>
    </Swatch>
  </Palette>


</MDH>
